name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Dispara o workflow apenas quando houver push na branch "main"
  pull_request:
    branches:
      - main  # Dispara o workflow quando houver um pull request para a branch "main"

jobs:
  # Job para rodar testes
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  # Job para construir e enviar a imagem Docker para o Docker Hub
  docker:
    runs-on: ubuntu-latest
    needs: test  # O job "docker" depende que o job "test" seja concluído com sucesso

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/blog-professores:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/blog-professores:latest
